apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-operator
spec:
  components:
    pilot:
      k8s:
        env:
        - name: SPIFFE_BUNDLE_ENDPOINTS
          value: "" # kpt-set: ${anthos.servicemesh.spiffe-bundle-endpoints}
        - name: ENABLE_STACKDRIVER_MONITORING
          value: "true"
        - name: TOKEN_AUDIENCES
          value: "" # kpt-set: ${anthos.servicemesh.token-audiences}
  meshConfig:
    trustDomainAliases: # kpt-set: ${setters.anthos.servicemesh.trustDomainAliases}
      - "cluster.local"
