registry: gcr.io/gke-release-staging
repos:
  - asm/pilot
  - asm/proxyv2
  - asm/install-cni
  - asm/mdp
  - asm/csm-mesh-proxy
  - csm/thc
versions:
  - name: 1.20.6-asm.0
    status: deprecated
  - name: 1.18.7-asm.26
    status: deprecated
  - name: 1.19.10-asm.6
    status: deprecated
  - name: 1.20.7-asm.2
    status: deprecated
  - name: 1.21.3-asm.3
    status: deprecated
  - name: 1.21.4-asm.0
    status: deprecated
  - name: 1.18.7-asm.27
    status: deprecated
  - name: 1.19.10-asm.9
    status: deprecated
  - name: 1.20.8-asm.1
    status: deprecated
  - name: 1.21.4-asm.5
    status: deprecated
  - name: 1.22.3-asm.1
    status: deprecated
  - name: 1.18.7-asm.28
    status: deprecated
  - name: 1.19.10-asm.17
    status: deprecated
  - name: 1.20.8-asm.6
    status: deprecated
  - name: 1.21.5-asm.5
    status: deprecated
  - name: 1.22.4-asm.0
    status: deprecated
  - name: 1.20.8-asm.7
    status: deprecated
  - name: 1.21.5-asm.7
    status: deprecated
  - name: 1.22.5-asm.1
    status: deprecated
  - name: 1.23.2-asm.2
    status: deprecated
  - name: 1.18.7-asm.31
    status: deprecated
  - name: 1.19.10-asm.21
    status: deprecated
  - name: 1.20.8-asm.9
    status: deprecated
  - name: 1.21.5-asm.10
    status: deprecated
  - name: 1.22.6-asm.1
    status: deprecated
  - name: 1.23.3-asm.1
    status: deprecated
  - name: 1.20.8-asm.10
    status: deprecated
  - name: 1.21.5-asm.12
    status: live
  - name: 1.22.6-asm.2
    status: live
  - name: 1.23.3-asm.2
    status: live
  - name: 1.29.9-gke.3
    status: live
  - name: 1.28.7-gke.3
    status: live
  - name: 1.27.7-gke.3
    status: live
  - name: 1.21.5-1
    status: live
  - name: 956c6e3_20241121_2249
    status: live
  - name: 1.19.10-asm.22
    status: live
  - name: 1.20.8-asm.12
    status: live