apiVersion: sut.tailorbird.io/v1alpha1
kind: Rookery
metadata:
  name: asm-ci-aks-sc
  namespace: tailorbird-users
spec:
  ttlSeconds: 10800 # 3 hours
  knests:
  - apiVersion: sut.tailorbird.io/v1alpha1
    kind: Knest
    metadata:
      name: asm-ci-aks-sc-knest
    spec:
      clusters:
      - apiVersion: sut.tailorbird.io/v1alpha1
        kind: Cluster
        metadata:
          name: asm-ci-aks-sc-cluster
        spec:
          provider: azure
          distribution: aks
          provisionerArgs:
            region: centralus
            {{- if eq .Version "latest" }}
            kubernetesVersion: "1.28"
            {{- else if .Version}}
            kubernetesVersion: "{{ .Version }}"
            {{- else }}
            kubernetesVersion: "1.28"
            {{- end }}
            username: asm-svc-acct
            compressArtifacts: "true"
            nodeVmSize: "Standard_D8_v3"
