apiVersion: sut.tailorbird.io/v1alpha1
kind: Rookery
metadata:
  name: asm-ci-aws-sc-1p
  namespace: tailorbird-users
spec:
  ttlSeconds: 10800 # 3 hours
  knests:
    - apiVersion: sut.tailorbird.io/v1alpha1
      kind: Knest
      metadata:
        name: asm-ci-aws-sc-1p-knest
      spec:
        clusters:
          - apiVersion: sut.tailorbird.io/v1alpha1
            kind: Cluster
            metadata:
              name: asm-ci-aws-sc-1p-cluster
            spec:
              provider: aws
              distribution: gke-1p
              provisionerArgs:
                useDynamicTopology: "true"
                nodeCount: "3"
                {{- if eq .Version "latest" }}
                kubernetesVersion: 1.28.5-gke.100
                {{- else if .Version }}
                kubernetesVersion: "{{ .Version }}"
                {{- else }}
                kubernetesVersion: 1.28.5-gke.100
                {{- end }}
                username: asm-svc-acct
                nodepoolPatch: |
                  {
                    "config": {
                      "instanceType": "t3.large"
                    }
                  }
