apiVersion: sut.tailorbird.io/v1alpha1
kind: Rookery
metadata:
  name: asm-ci-azure-sc-1p
  namespace: tailorbird-users
spec:
  ttlSeconds: 7200 # 2 hours
  knests:
    - apiVersion: sut.tailorbird.io/v1alpha1
      kind: Knest
      metadata:
        name: asm-ci-azure-sc-1p-knest
      spec:
        clusters:
          - apiVersion: sut.tailorbird.io/v1alpha1
            kind: Cluster
            metadata:
              name: asm-ci-azure-sc-1p-cluster
            spec:
              provider: azure
              distribution: gke
              provisionerArgs:
                nodeCount: "3"
                {{- if eq .Version "latest" }}
                kubernetesVersion: 1.26.2-gke.1001
                {{- else if .Version }}
                kubernetesVersion: "{{ .Version }}"
                {{- else }}
                kubernetesVersion: 1.26.2-gke.1001
                {{- end }}
                username: asm-svc-acct
                nodepoolPatch: |
                  {
                    "config": {
                      "vmSize": "Standard_B2ms"
                    }
                  }
