apiVersion: sut.tailorbird.io/v1alpha1
kind: Rookery
metadata:
  # !!!IMPORTANT!!!! READ BELOW
  # Use names that are unique and easily identifiable
  # To see list of currently running rookeries:
  # kubectl get rookeries -n tailorbird-users
  # e.g., use your Google username as prefix.
  # !!!IMPORTANT!!!! READ ABOVE
  name: asm-baremetal-mcmn-rookery-1
  namespace: tailorbird-users
spec:
  knests:
  - apiVersion: sut.tailorbird.io/v1alpha1
    kind: Knest
    metadata:
      name: asm-baremetal-mcmn-knest-1
    spec:
      clusters:
      - apiVersion: sut.tailorbird.io/v1alpha1
        kind: Cluster
        metadata:
          # !!!IMPORTANT!!!! READ BELOW
          # Use names that are unique and easily identifiable
          # To see list of currently running clusters:
          # kubectl get clusters -n tailorbird-users
          # e.g., use your Google username as prefix.
          # !!!IMPORTANT!!!! READ ABOVE
          name: asm-baremetal-mcmn-cluster-1
          namespace: tailorbird-users
        spec:
          provider: baremetal
          distribution: gke
          provisionerArgs:
            username: asmprowuser
            bmctlVersion: "{{ .Version }}"
            bmctlVersionPrefix: "{{ .VersionPrefix }}"
            passthroughEnv: |
              {
                 "MANIFEST_PROFILE_ENV": "staging",
                 "NUM_GCE_VIPS": "2"
              }
      - apiVersion: sut.tailorbird.io/v1alpha1
        kind: Cluster
        metadata:
          # !!!IMPORTANT!!!! READ BELOW
          # Use names that are unique and easily identifiable
          # To see list of currently running clusters:
          # kubectl get clusters -n tailorbird-users
          # e.g., use your Google username as prefix.
          # !!!IMPORTANT!!!! READ ABOVE
          name: asm-baremetal-mcmn-cluster-2
          namespace: tailorbird-users
        spec:
          provider: baremetal
          distribution: gke
          provisionerArgs:
            username: asmprowuser
            bmctlVersion: "{{ .Version }}"
            bmctlVersionPrefix: "{{ .VersionPrefix }}"
            passthroughEnv: |
              {
                 "MANIFEST_PROFILE_ENV": "staging",
                 "NUM_GCE_VIPS": "2"
              }
