apiVersion: sut.tailorbird.io/v1alpha1
kind: Rookery
metadata:
  # !!!IMPORTANT!!!! READ BELOW
  # Use names that are unique and easily identifiable
  # To see list of currently running rookeries:
  # kubectl get rookeries -n tailorbird-users
  # e.g., use your Google username as prefix.
  # !!!IMPORTANT!!!! READ ABOVE
  name: asm-baremetal-scsn-rookery-1-kubevirt-vm
  namespace: tailorbird-users
spec:
  ttlSeconds: 7200 # 2 hours
  knests:
  - apiVersion: sut.tailorbird.io/v1alpha1
    kind: Knest
    metadata:
      name: asm-baremetal-scsn-knest-1-kubevirt-vm
    spec:
      clusters:
      - apiVersion: sut.tailorbird.io/v1alpha1
        kind: Cluster
        metadata:
          # !!!IMPORTANT!!!! READ BELOW
          # Use names that are unique and easily identifiable
          # To see list of currently running clusters:
          # kubectl get clusters -n tailorbird-users
          # e.g., use your Google username as prefix.
          # !!!IMPORTANT!!!! READ ABOVE
          name: asm-baremetal-scsn-cluster-1-kubevirt-vm
          namespace: tailorbird-users
        spec:
          provider: baremetal
          distribution: gke
          provisionerArgs:
            username: prowuser
            bmctlVersion: "{{ .Version }}"
            bmctlVersionPrefix: "{{ .VersionPrefix }}"
            passthroughEnv: |
              {
                "MANIFEST_PROFILE_ENV": "staging",
                "USE_EMULATION": "false"
              }
