apiVersion: sut.tailorbird.io/v1alpha1
kind: Rookery
metadata:
  name: asm-ci-eks-sc
  namespace: tailorbird-users
spec:
  ttlSeconds: 10800 # 3 hours
  knests:
  - apiVersion: sut.tailorbird.io/v1alpha1
    kind: Knest
    metadata:
      name: asm-ci-eks-sc-knest
    spec:
      clusters:
      - apiVersion: sut.tailorbird.io/v1alpha1
        kind: Cluster
        metadata:
          name: asm-ci-eks-sc-cluster
        spec:
          provider: aws
          distribution: eks
          provisionerArgs:
            auth: "SAToken"
            {{- if eq .Version "latest" }}
            kubernetesVersion: "1.27"
            {{- else if .Version}}
            kubernetesVersion: "{{ .Version }}"
            {{- else }}
            kubernetesVersion: "1.27"
            {{- end }}
            username: asm-svc-acct
            compressArtifacts: "true"
            nodeType: "t3.large"
            nodeCount: "4"
