apiVersion: sut.tailorbird.io/v1alpha1
kind: Rookery
metadata:
 name: asm-ci-onprem-sc
 namespace: tailorbird-users
spec:
 ttlSeconds: 21600 # 6 hours
 knests:
 - apiVersion: sut.tailorbird.io/v1alpha1
   kind: Knest
   metadata:
     name: asm-ci-onprem-sc-knest
   spec:
     clusters:
     - apiVersion: sut.tailorbird.io/v1alpha1
       kind: Cluster
       metadata:
         name: asm-ci-onprem-sc-cluster
       spec:
         provider: vsphere
         distribution: gke
         provisionerArgs:
           username: prowuser
           {{- if .Version }}
           gkectlVersion: "{{ .Version }}"
           {{- end }}
           {{- if .VersionPrefix }}
           gkectlVersionPrefix: "{{ .VersionPrefix }}"
           releaseMode: "true"
           useStagingBucket: "true"
           {{- end }}
           gkectlConfigSeedVersion: "v1"
           vipNetwork: "fe"
           gkeConnectProject: "{{ .OnPremHubDevProject }}"
           stackdriverProjectId: "{{ .OnPremHubDevProject }}"
           # gkeConnectSA: "{{ .OnPremGkeConnectSA }}"
           herculesEnvTtl: "4h"
           vsphereVersion: "7.0"
           esxiVersion: "7.0"
