apiVersion: sut.tailorbird.io/v1alpha1
kind: Rookery
metadata:
  # !!!IMPORTANT!!!! READ BELOW
  # Use names that are unique and easily identifiable
  # To see list of currently running rookeries:
  # kubectl get rookeries -n tailorbird-users
  # To view existing knests:
  # kubectl get knests -n tailorbird-users
  # To view existing clusters:
  # kubectl get clusters.sut.tailorbird.io -n tailorbird-users
  # e.g., use your Google username as prefix.
  # !!!IMPORTANT!!!! READ ABOVE
  name: asm-ci-onprem-hub-mcmn-uci
  namespace: tailorbird-users
spec:
  ttlSeconds: 10800 # 3 hours
  knests:
    - apiVersion: sut.tailorbird.io/v1alpha1
      kind: Knest
      metadata:
        name: asm-ci-onprem-hub-mcmn-uci-knest
      spec:
        clusters:
          # TODO(tairan): use two clusters after b/176177944 is fixed
          - apiVersion: sut.tailorbird.io/v1alpha1
            kind: Cluster
            metadata:
              name: asm-ci-onprem-hub-mcmn-uci-cluster-01
            spec:
              provider: vsphere
              distribution: gke
              provisionerArgs:
                lbkind: "MetalLB"
                username: prowuser
                ipAllocationStrategy: static
                workerNumNodes: "4"
                {{- if .Version }}
                gkectlVersion: "{{ .Version }}"
                {{- end }}
                {{- if .VersionPrefix }}
                gkectlVersionPrefix: "{{ .VersionPrefix }}"
                releaseMode: "true"
                useStagingBucket: "true"
                {{- end }}
                connectLocation: us-central1
                # workaround for b/181781346
                gkectlConfigSeedVersion: "v1"
                gkeConnectProject: "{{ .OnPremHubDevProject }}"
                stackdriverProjectId: "{{ .OnPremHubDevProject }}"
                # gkeConnectSA: "{{ .OnPremGkeConnectSA }}"
                vsphereVersion: "7.0"
                esxiVersion: "7.0"
                controlPlaneV2Enabled: "true"
                userAcnMode: "true"
          - apiVersion: sut.tailorbird.io/v1alpha1
            kind: Cluster
            metadata:
              name: asm-ci-onprem-hub-mcmn-uci-cluster-02
            spec:
              provider: vsphere
              distribution: gke
              provisionerArgs:
                lbkind: "MetalLB"
                ipAllocationStrategy: static
                username: prowuser
                workerNumNodes: "4"
                {{- if .Version }}
                gkectlVersion: "{{ .Version }}"
                {{- end }}
                {{- if .VersionPrefix }}
                gkectlVersionPrefix: "{{ .VersionPrefix }}"
                releaseMode: "true"
                useStagingBucket: "true"
                {{- end }}
                connectLocation: us-central1
                # workaround for b/181781346
                gkectlConfigSeedVersion: "v1"
                gkeConnectProject: "{{ .OnPremHubDevProject }}"
                stackdriverProjectId: "{{ .OnPremHubDevProject }}"
                # gkeConnectSA: "{{ .OnPremGkeConnectSA }}"
                vsphereVersion: "7.0"
                controlPlaneV2Enabled: "true"
                userAcnMode: "true"
                esxiVersion: "7.0"
