apiVersion: sut.tailorbird.io/v1alpha1
kind: Rookery
metadata:
  creationTimestamp: null
  name: asm-baremetal-hybrid-rookery
  namespace: tailorbird-users
spec:
  ttlSeconds: 10800 # 3 hours
  knests:
  - apiVersion: sut.tailorbird.io/v1alpha1
    kind: Knest
    metadata:
      creationTimestamp: null
      name: asm-baremetal-hybrid-knest
    spec:
      clusters:
      - apiVersion: sut.tailorbird.io/v1alpha1
        kind: Cluster
        metadata:
          creationTimestamp: null
          name: asm-baremetal-hybrid-bm-cluster-01
          namespace: tailorbird-users
        spec:
          distribution: gke
          provider: baremetal
          provisionerArgs:
            bmctlVersion: "latest"
            bmctlVersionPrefix: "1.13"
            # bmctlVersion: "{{ .Version }}"
            # bmctlVersionPrefix: "{{ .VersionPrefix }}"
            passthroughEnv: |
              {
                "NUM_GCE_VIPS": "2",
                "SUBNET": "baremetal-internal-01",
                "MANIFEST_PROFILE_ENV": "staging",
                "NETWORK_TAGS": "baremetal-hybrid",
                "CONTROLPLANE_USE_GCE_VIP": "1"
              }
            project: {{ .OnPremHubDevProject }}
            proxyPort: "8218"
            scriptsVersion: latest
            scriptsVersionPrefix: "0.0"
            username: asm-svc-acct
        status: {}
      - apiVersion: sut.tailorbird.io/v1alpha1
        kind: Cluster
        metadata:
          creationTimestamp: null
          name: asm-baremetal-hybrid-gcp-cluster-01
        spec:
          distribution: gke
          provider: gcp
          provisionerArgs:
            pluginSpecYaml: |
              pluginOptions:
                # note: this currently leaves orphan firewall rules, needs some sort of janitor
                skipNetworkTeardowns: true
              projectOptions:
                projects: {{ .OnPremHubDevProject }}
              networkOptions:
                network: cluster-net
              clusterOptions:
                clusters: test-cluster-gkebm-hybrid-01
                regions: us-central1
                gcloudExtraFlags: --enable-ip-alias --subnetwork=cluster-internal-01
                workloadIdentityEnabled: true
        status: {}
    status: {}
status: {}
