# prepare a distroless source context to copy files from
# hadolint ignore=DL3026
FROM gke.gcr.io/gke-distroless/libc:gke_distroless_20250107.00_p0@sha256:1815080f790e160ae891eb733b8302ae04f4cefe4f872ed0bf6dc3f61e80e0e0 as distroless_source

# prepare a base dev to modify file contents
# hadolint ignore=DL3007,DL3026
FROM marketplace.gcr.io/google/ubuntu2404:latest@sha256:f226b52ce8f8365aa0a52fb8f4392ecbe1c215639f73edf16a12e5f3d6765147 AS ubuntu_source

# Modify contents of container
COPY --from=distroless_source /etc/ /home/etc
COPY --from=distroless_source /home/nonroot /home/nonroot
RUN echo istio-proxy:x:1337: >> /home/etc/group
RUN echo istio-proxy:x:1337:1337:istio-proxy:/nonexistent:/sbin/nologin >> /home/etc/passwd

# Customize distroless with the following:
# - password file
# - groups file
# - /home/nonroot directory
FROM distroless_source
COPY --from=ubuntu_source /home/etc/passwd /etc/passwd
COPY --from=ubuntu_source /home/etc/group /etc/group
COPY --from=ubuntu_source /home/nonroot /home/nonroot
