# hadolint ignore=DL3026
FROM gke.gcr.io/gke-distroless/libc:gke_distroless_20250407.00_p0@sha256:df9f8d65bb5f790b8b659bfb7f019584a1f1b5be4d56e4c7442353dae75baf77 AS distroless_libc

# hadolint ignore=DL3026
FROM us.gcr.io/gke-release/debian-base:bookworm-v1.0.4-gke.5@sha256:645f60901185d00d286326f86565db7ef8f633ae6d06e4d4d20f1d49207d94fb AS pkgs

ARG PKGS="ca-certificates-bundle iptables ip6tables libnetfilter_conntrack libnfnetlink libmnl"

WORKDIR /tmp

# hadolint ignore=DL4006,SC2086
RUN apt-get update \
    && apt-get download $(apt-cache depends --recurse -i ${PKGS} | grep '^\w') \
    && mkdir -p /dpkg/var/lib/dpkg/status.d/ \
    && for deb in *.deb; do \
        package_name=$(dpkg-deb -I ${deb} | awk '/^ Package: .*$/ {print $2}'); \
        dpkg --ctrl-tarfile $deb | tar -Oxf - ./control > /dpkg/var/lib/dpkg/status.d/${package_name}; \
        dpkg --extract $deb /dpkg || exit 10; \
    done \
    && find /dpkg/ -type d -empty -delete \
    && rm -r /dpkg/usr/share/doc/ \
    && find /dpkg/

WORKDIR /dpkg/usr/sbin/
RUN mkdir /dpkg/run && chmod 755 /dpkg/run

RUN ln -s iptables-legacy iptables \
    && ln -s iptables-legacy-restore iptables-restore \
    && ln -s iptables-legacy-save iptables-save \
    && ln -s ip6tables-legacy ip6tables \
    && ln -s ip6tables-legacy-restore ip6tables-restore \
    && ln -s ip6tables-legacy-save ip6tables-save

FROM distroless_libc
COPY --from=pkgs ["/dpkg/", "/"]

USER 65532
