apiVersion: networking.istio.io/v1alpha3
kind: WorkloadGroup
metadata:
  name: vm-v1
  namespace: test-ns1
spec:
  metadata:
    annotations:
      security.cloud.google.com/IdentityProvider: google
    labels:
      app: vm
      version: v1
  template:
    ports:
      http: 8090
      tcp: 9090
      grpc: 7070
      https: 8443
