---
# Source: mdp/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mdp-controller
  namespace: kube-system
  labels:
    app: mdp-controller
    release: mdp
    istio.io/rev: default
    install.operator.istio.io/owning-resource: unknown
    operator.istio.io/component: "Cni"
---
# Source: mdp/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mdp-controller
  labels:
    app: mdp-controller
rules:
- apiGroups:
  - mesh.cloud.google.com
  resources:
  - 'controlplanerevisions'
  - 'dataplanecontrols'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mesh.cloud.google.com
  resources:
  - 'dataplanecontrols/status'
  verbs:
  - get
  - list
  - watch
  - delete
  - patch
  - update
  - create
- apiGroups:
  - apps
  - extensions
  resources:
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - patch
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/eviction
  verbs:
  - get
  - list
  - watch
  - delete
  - patch
  - update
  - create
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
---
# Source: mdp/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mdp-controller
  labels:
    app: mdp-controller
subjects:
- kind: ServiceAccount
  name: mdp-controller
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: mdp-controller
  apiGroup: rbac.authorization.k8s.io
---
# Source: mdp/templates/deployment-mdp.yaml
# This manifest installs the ASM managed data plane in-cluster controller.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mdp-controller
  namespace: kube-system
  labels:
    app: mdp-controller
    sidecar.istio.io/inject: "false"
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mdp-controller
  template:
    metadata:
      labels:
        app: mdp-controller
        sidecar.istio.io/inject: "false"
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
      # Mark the pod as a critical add-on for rescheduling.
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        operator: Exists
      priorityClassName: system-node-critical
      serviceAccountName: mdp-controller
      # Minimize downtime during a rolling upgrade or deletion; tell Kubernetes to do a "force
      # deletion": https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods.
      terminationGracePeriodSeconds: 5
      containers:
      - name: mdp-controller
        image: "{{ .MDP_HUB }}/mdp:{{ .MDP_TAG }}"
        command:
        - mdp
        - server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 1337
          runAsUser: 1337
          runAsNonRoot: true
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 400m
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 128Mi
        env:
        - name: WATCH_NAMESPACE
          value: "istio-system"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - mountPath: /var/run/secrets/tokens
          name: istio-token
      volumes:
      - name: istio-token
        projected:
          sources:
          - serviceAccountToken:
              path: istio-token
              expirationSeconds: 43200
              audience: PROJECT_ID.svc.id.goog
