apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-operator
spec:
  values:
    pilot:
      env:
        PILOT_ENABLE_ALPHA_GATEWAY_API: "true" # enable alpha APIs in the Kubernetes gateway-api
    telemetry:
      v2:
        prometheus:
          enabled: true
  meshConfig:
    defaultConfig:
      gatewayTopology:
        numTrustedProxies: 1
