apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    mdp:
      enabled: true
  components:
    cni:
      enabled: true
      k8s:
        overlays:
          - kind: DaemonSet
            name: istio-cni-node
            patches:
              - path: spec.template.spec.containers.[name:mdp-controller].env.[100]
                value: |
                  name: MDP_RECONCILE_TIME
                  value: "1m"

