---
apiVersion: v1
kind: Service
metadata:
 name: istio-egressgateway
spec:
 type: ClusterIP
 selector:
   istio: egressgateway
 ports:
 - name: http2
   port: 80
   protocol: TCP
   targetPort: 8080
 - name: https
   port: 443
   protocol: TCP
   targetPort: 8443
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: istio-egressgateway
spec:
 selector:
   matchLabels:
     istio: egressgateway
 template:
   metadata:
     annotations:
       # This is required to tell Anthos Service Mesh to inject the gateway with the
       # required configuration.
       inject.istio.io/templates: gateway
     labels:
       istio: egressgateway
       istio.io/rev: asm-managed # This is required only if the namespace is not labeled.
   spec:
     containers:
     - name: istio-proxy
       image: auto # The image will automatically update each time the pod starts.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: istio-egressgateway-sds
  namespace: istio-system
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: istio-egressgateway-sds
  namespace: istio-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: istio-egressgateway-sds
subjects:
- kind: ServiceAccount
  name: default

